version: "3.8"
services:
  app:
    build:
      context: ./
    restart: 'no'
    networks:
      - dgraphnet
    ports:
      - 8080:8080
    environment:
      DB_HOST: db:8080
      LOG_LEVEL: DEBUG
    depends_on:
      db_init:
        condition: service_completed_successfully
    user: root # For attaching VSCode
    command: tail -f /dev/null
    volumes:
      - ./src:/app

  db:
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet
    
  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-3914aa2
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      TIMEOUT: 25
      DGRAPH_SERVER: http://db:8080
      # SAMPLE_DATA: plain_pubs

networks:
  dgraphnet:
